# Generated by Django 4.1.5 on 2023-02-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryClientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_clients_model', models.CharField(max_length=255)),
                ('directory_clients_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryMalfunctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_malfunction_type', models.CharField(max_length=255)),
                ('directory_malfunction_type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryRepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_repair_type', models.CharField(max_length=255)),
                ('directory_repair_type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_service_provider', models.CharField(max_length=255)),
                ('directory_service_provider_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_service_provider', models.CharField(max_length=255)),
                ('directory_service_provider_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryVehicleDeadAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_vehicle_dead_axle_model', models.CharField(max_length=255)),
                ('directory_vehicle_dead_axle_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryVehicleEngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_vehicle_engine_model', models.CharField(max_length=255)),
                ('directory_vehicle_engine_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryVehicleLiveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_vehicle_live_axle_model', models.CharField(max_length=255)),
                ('directory_vehicle_live_axle_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryVehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_vehicle_model', models.CharField(max_length=255)),
                ('directory_vehicle_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryVehicleTransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_vehicle_transmission_model', models.CharField(max_length=255)),
                ('directory_vehicle_transmission_model_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_serial_number', models.CharField(max_length=255)),
                ('vehicle_engine_serial_number', models.CharField(max_length=255)),
                ('vehicle_transmission_serial_number', models.CharField(max_length=255)),
                ('vehicle_live_axle_serial_number', models.CharField(max_length=255)),
                ('vehicle_dead_axle_serial_number', models.CharField(max_length=255)),
                ('vehicle_invoice', models.CharField(max_length=255)),
                ('vehicle_shipping_date', models.DateTimeField()),
                ('vehicle_end_user', models.CharField(max_length=255)),
                ('vehicle_shipping_address', models.CharField(max_length=255)),
                ('vehicle_options', models.CharField(max_length=255)),
                ('vehicle_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryclientsmodel')),
                ('vehicle_dead_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryvehicledeadaxlemodel')),
                ('vehicle_engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryvehicleenginemodel')),
                ('vehicle_live_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryvehicleliveaxlemodel')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryvehiclemodel')),
                ('vehicle_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryserviceprovider')),
                ('vehicle_transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryvehicletransmissionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField()),
                ('service_engine_hours', models.IntegerField()),
                ('service_order_number', models.CharField(max_length=255)),
                ('service_order_date', models.DateTimeField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryserviceprovider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryservicetype')),
                ('service_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamation_date', models.DateTimeField()),
                ('reclamation_engine_hours', models.CharField(max_length=255)),
                ('reclamation_malfunction_description', models.CharField(max_length=255)),
                ('reclamation_replacement_parts', models.CharField(max_length=255)),
                ('reclamation_repair_date', models.DateTimeField()),
                ('reclamation_malfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directorymalfunctiontype')),
                ('reclamation_repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryrepairtype')),
                ('reclamation_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.directoryserviceprovider')),
                ('reclamation_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_portal.vehicle')),
            ],
        ),
    ]
